language: node_js
node_js:
  - lts/*
cache: npm install
jobs:
  include:
    - stage: test
      script:
        - npm ci
        - npm run lint
        - npm run test
    - stage: deploy
      if: branch = master AND type != pull_request
      script:
        - npm run semantic-release
stages:
  - test
  - deploy