language: node_js
node_js:
  - 9.5

cache:
  directories:
  - "$HOME/.npm"

install:
  - npm ci  # Does the same thing as npm install without changing the package-lock.json

script:
  - npm run test
  - npm run lint

deploy:
  provider: npm
  email: chow.ruijie@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master 